# Generated by Django 6.0.1 on 2026-01-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinos', '0003_alter_treinoitem_exercicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INICIADA', 'Iniciada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='INICIADA', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='treinos.treino')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_real', models.CharField(blank=True, max_length=30)),
                ('repeticoes_reais', models.CharField(blank=True, max_length=20)),
                ('rpe', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('treino_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_itens', to='treinos.treinoitem')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='execucoes.sessaotreino')),
            ],
            options={
                'unique_together': {('sessao', 'treino_item')},
            },
        ),
    ]
