# Generated by Django 6.0.1 on 2026-01-27 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(choices=[('INICIANTE', 'Iniciante'), ('INTERMEDIARIO', 'Intermediário'), ('AVANCADO', 'Avançado')], default='INICIANTE', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios', to='exercicios.equipamento')),
                ('musculos_principais', models.ManyToManyField(blank=True, related_name='exercicios_principais', to='exercicios.musculo')),
                ('musculos_secundarios', models.ManyToManyField(blank=True, related_name='exercicios_secundarios', to='exercicios.musculo')),
            ],
        ),
    ]
