# Generated by Django 6.0.1 on 2026-01-27 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEMPLATE', 'Template (genérico)'), ('ALUNO', 'Específico do aluno')], max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treinos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio_nome', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticoes', models.CharField(default='8-12', max_length=20)),
                ('carga', models.CharField(blank=True, max_length=30)),
                ('descanso_seg', models.PositiveIntegerField(default=60)),
                ('observacoes', models.TextField(blank=True)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='treinos.treino')),
            ],
        ),
    ]
