# Generated by Django 6.0.1 on 2026-01-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinoitem',
            name='exercicio_nome',
        ),
        migrations.AddField(
            model_name='treinoitem',
            name='exercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_treino', to='exercicios.exercicio'),
        ),
    ]
