# Generated by Django 6.0.1 on 2026-01-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        ('treinos', '0002_remove_treinoitem_exercicio_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinoitem',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_treino', to='exercicios.exercicio'),
        ),
    ]
